apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: img-rec-dev
description: main application pipeline
serialPipeline:
  stages:
  - targetId: img-rec-dev-target-alpha
    profiles: []
  # - targetId: qsprod
  #   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: img-rec-dev-target-alpha
description: development cluster
gke:
  cluster: projects/imgrec-395114/locations/europe-central2/clusters/freecollclusteralpha
# ---

# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: qsprod
# description: production cluster
# gke:
#   cluster: projects/imgrec-395114/locations/us-central1/clusters/quickstart-cluster-qsprod